service: fleetmetrica

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  versionFunctions: false
  stage: dev
  region: us-east-1
  memorySize: 128

functions:
  fleetmocker:
    handler: handler.fleetmocker
