service: fleetmetrica

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  versionFunctions: false
  stage: dev
  region: us-east-1
  memorySize: 128
  timeout: 600

functions:
  fleetmocker:
    handler: handler.fleetmocker


plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

package:
  exclude:
    - node_modules/**
    - venv/**
    - mocks/**
    - .idea/**